repos:
#- repo: https://github.com/ansys/pre-commit-hooks
#  rev: v0.5.1
#  hooks:
#    - id: add-license-headers
#      name: Add license headers (sh)
#      args:
#        - --custom_copyright=i-Cell Mobilsoft Zrt.
#        - --custom_license=Apache-2.0
#        - --start_year=2025
#        - --custom_template=apache.jinja2
#        - --parser=shell
#      files: '^(etc|liquibase)/.*\.(sh)$'
- repo: local
  hooks:
  - id: add-license-header
    name: Add License Header
    entry: reuse annotate --license 'Apache-2.0' --copyright '(C) i-Cell Mobilsoft Zrt.' --year '2023' --template 'apache.jinja2' --copyright-prefix string .
#    entry: reuse annotate --copyright='(C) i-Cell Mobilsoft Zrt.' --license='Apache-2.0' etc/
    language: system
    types: [file]
    files: '^(etc|liquibase)/.*\.(sh)$'
#  - id: add-license-header-sql
#    name: Add License Header Liquibase files
#    entry: reuse annotate --license="Apache-2.0" --copyright="(C) i-Cell Mobilsoft Zrt." --year 2023 --template apache.jinja2 liquibase
#    language: system
#    types: [file]
#    files: \.(sh|yaml|yml|xml|dtd)$
