repos:
- repo: local
  hooks:
#  - id: echo
#    name: Add License Header Docker files
#    entry: echo $PWD > ./pwd
#    language: system
#    types: [file]
#    files: \.(sh|yaml|yml|xml|dtd)$
  - id: add-license-header-docker
    name: Add License Header Docker files
    entry: reuse annotate --license="Apache-2.0" --copyright="(C) 2023 i-Cell Mobilsoft Zrt." --template apache.jinja2 etc
    language: system
    types: [file]
    files: \.(sh|yaml|yml|xml|dtd)$
  - id: add-license-header-sql
    name: Add License Header Liquibase files
    entry: reuse annotate --license="Apache-2.0" --copyright="(C) 2023 i-Cell Mobilsoft Zrt." --template apache.jinja2 liquibase
    language: system
    types: [file]
    files: \.(sh|yaml|yml|xml|dtd)$
