= Development guide

== Development
=== Used tools, scripts

====
.Available Liquibase changefile types (_click here_) 
[%collapsible]
======
*Liquibase header:*

. Postgres/Oracle liquibase header XML version:
[source,xml]
<?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE defaultProperties SYSTEM "common/params.dtd">
    <databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
        http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.3.xsd">        
    <!-- include the default properties -->
    &propertiesAll;
   <changeSet id="0007" author="jozsef.holczer" labels="0.1.0">
   <comment>UM-116-Creating UM_GROUP table...</comment>

. Oracle liquibase header SQL version:
[source,sql]
--liquibase formatted sql
--changeset developer.name:0002 labels:0.3.0 dbms:oracle
--comment PROJECT-504 Creating INTERVAL_DECLARATION_DATA table

. Postgresql liquibase header SQL version:
[source,sql]
--liquibase formatted sql
--changeset developer.name:0002 labels:0.3.0 dbms:postgresql
--comment PROJECT-504 Creating INTERVAL_DECLARATION_DATA table

*Create Table part without BLOB or Partition:*
//A paragraph with the [%hardbreaks] option preserves line breaks
[%hardbreaks]
IMPORTANT: The global DB specific variables, e.g. "${schema_name}", are taken from the "params.dtd" file in the above XML header and are dynamically substituted at runtime.

. Postgres/Oracle create table XML version:
[source,xml]
<createTable tableName = "um_group" remarks = "Group storage table." schemaName = "${schema_name}">
    <column name = "x__id" type = "varchar2(30 ${char})"  remarks = "PK"><constraints nullable = "false" /></column>
    <column name = "group_type" type = "varchar2(30 ${char})"  remarks = "The field indicates whether it's a group created in LDAP or individually on the project page. A check constraint should be placed on the field, with values: LDAP, CUSTOM"><constraints nullable = "false" /></column>
    <column name = "group_name" type = "varchar2(255 ${char})"  remarks = "Name of the group"><constraints nullable = "false" /></column>
    <column name = "x__insdate" type = "${datetime}" defaultValueComputed = "${sysdate}"  remarks = "Insert timestamp"><constraints nullable = "false" /></column>
    <column name = "x__insuser" type = "varchar2(30 ${char})" defaultValue = "0"  remarks = "ID of the User who created the record (X__ID)"><constraints nullable =false" /></column>
    <column name = "x__moddate" type = "${datetime}"  remarks = "Modification timestamp"></column>
    <column name = "x__moduser" type = "varchar2(30 ${char})"  remarks = "ID of the User who modified the record (X__ID)"></column>
    <column name = "x__version" type = "${versionDataType}" defaultValueNumeric = "0"  remarks = "Change version"><constraints nullable = "false" /></column>
</createTable>
<createIndex indexName="ix_nf_processing_data_id" tableName="nf_processing" schemaName="${schema_name}">
    <column name="nf_data_id"/>
</createIndex>  
<addPrimaryKey columnNames="x__id" constraintName="pk_um_group_to_role" tableName="um_group_to_role" schemaName="${schema_name}" />
<addForeignKeyConstraint                                         
    baseColumnNames="um_group_id"                             
    baseTableName="um_group_to_role"                           
    baseTableSchemaName="${schema_name}"                         
    constraintName="fk_um_group_to_role_um_group"   
    referencedColumnNames="x__id"                                  
    referencedTableName="um_group"                      
    referencedTableSchemaName="${schema_name}"/>                 
<addForeignKeyConstraint                                         
    baseColumnNames="um_role_id"                             
    baseTableName="um_group_to_role"                           
    baseTableSchemaName="${schema_name}"                         
    constraintName="fk_um_group_to_role_um_role"   
    referencedColumnNames="x__id"                                  
    referencedTableName="um_role"                      
    referencedTableSchemaName="${schema_name}"/>                 
<createIndex indexName = "ix_um_group_to_role_um_group_id" tableName = "um_group_to_role" schemaName = "${schema_name}">
    <column name = "um_group_id"/>
 </createIndex>
<createIndex indexName = "ix_um_group_to_role_um_role_id" tableName = "um_group_to_role" schemaName = "${schema_name}">
    <column name = "um_role_id"/>
 </createIndex>

. Oracle create table SQL version:
[source,sql]
create table INTERVAL_DECLARATION_DATA
(
   x__id                            VARCHAR2(30 CHAR) not null,
   interval_declaration_id          VARCHAR2(30 CHAR) not null,
   x__insdate                       DATE default SYSDATE not null,
   x__insuser                       VARCHAR2(30 CHAR) default '0' not null,
   x__moddate                       DATE,
   x__moduser                       VARCHAR2(30 CHAR),
   x__version                       NUMBER default 0 not null
);
comment on table INTERVAL_DECLARATION_DATA is 'Field-level aggregated data of declarations as BLOB';
comment on column INTERVAL_DECLARATION_DATA.x__id is 'PK (generated)';
--.....
alter table INTERVAL_DECLARATION_DATA add constraint PK_INTERVAL_DECLARATION_DATA primary key (x__id);
alter table INTERVAL_DECLARATION_DATA add constraint FK_INTERVAL_DECLARATION_DATA_INTERVAL_DECLARATION foreign key (interval_declaration_id) references INTERVAL_DECLARATION (x__id);
create index IX_INTERVAL_DECLARATION_DATA_INTERVAL_DECLARATION ON INTERVAL_DECLARATION_DATA (interval_declaration_id);

. Postgresql create table SQL version:
[source,sql]
CREATE TABLE INTERVAL_DECLARATION_DATA
(
   x__id                    VARCHAR(30) PRIMARY KEY NOT NULL,
   interval_declaration_id   VARCHAR(30) NOT NULL,
   x__insdate               DATE DEFAULT current_date NOT NULL,
   x__insuser               VARCHAR(30) DEFAULT '0' NOT NULL,
   x__moddate               DATE,
   x__moduser               VARCHAR(30),
   x__version               INTEGER DEFAULT 0 NOT NULL
);
COMMENT ON TABLE INTERVAL_DECLARATION_DATA IS 'Field-level aggregated data of declarations as BLOB';
COMMENT ON COLUMN INTERVAL_DECLARATION_DATA.x__id IS 'PK (generált)';
--.....
ALTER TABLE INTERVAL_DECLARATION_DATA ADD CONSTRAINT PK_INTERVAL_DECLARATION_DATA PRIMARY KEY (x__id);
ALTER TABLE INTERVAL_DECLARATION_DATA ADD CONSTRAINT FK_INTERVAL_DECLARATION_DATA_INTERVAL_DECLARATION FOREIGN KEY (interval_declaration_id)
REFERENCES INTERVAL_DECLARATION (x__id);
CREATE INDEX IX_INTERVAL_DECLARATION_DATA_INTERVAL_DECLARATION ON INTERVAL_DECLARATION_DATA (interval_declaration_id);

*Create Table part with BLOB or/and Partition:*
//A paragraph with the [%hardbreaks] option preserves line breaks
[%hardbreaks]
IMPORTANT: If your table has a BLOB or partition, you must place the remarks or other key/constraint generating parts in a separate XML file! Global database-specific variables, such as "${schema_name}", come from the "params.dtd" included in the previous XML header and are dynamically replaced at runtime.

. Postgres/Oracle create table + BLOB + Partition XML version:
[source,xml]
<createTable tableName = "project_invoice_data" schemaName = "${schema_name}">
    <column name = "x__id" type = "varchar2(30 ${char})"  ><constraints nullable = "false" /></column>
    <column name = "project_invoice_id" type = "varchar2(30 ${char})"  ><constraints nullable = "false" /></column>
    <column name = "invoice_data" type = "${blob}"  ><constraints nullable = "false" /></column>
    <column name = "insdate_month" type = "${datetime}" defaultValueComputed = "to_date(to_char(${sysdate}, 'YYYY.MM'), 'YYYY.MM')"  ><constraints nullable = "false" /><olumn>
    <column name = "x__insdate" type = "${datetime}" defaultValueComputed = "${sysdate}"  ><constraints nullable = "false" /></column>
    <column name = "x__insuser" type = "varchar2(30 ${char})" defaultValue = "0"  ><constraints nullable = "false" /></column>
    <column name = "x__moddate" type = "${datetime}"  ></column>
    <column name = "x__moduser" type = "varchar2(30 ${char})"  ></column>
    <column name = "x__version" type = "${versionDataType}" defaultValueNumeric = "0"  ><constraints nullable = "false" /></column>
</createTable>
<modifySql dbms = "oracle">
    <append value = "lob(invoice_data) store as securefile "/>
    <append  value = " PARTITION BY RANGE (x__insdate) INTERVAL( NUMTOYMINTERVAL(1, 'MONTH') )( PARTITION p_start VALUES LESS THAN (TO_DATE('2023-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) )"/>
</mofySql>
<modifySql dbms = "postgresql">
    <append  value = " PARTITION BY RANGE (insdate_month); "/>
    <append  value = " SELECT partman.create_parent( 
        p_parent_table    => '${schema_name}.project_invoice_data',
        p_control         => 'insdate_month',
        p_type            => 'native',
        p_interval        => 'monthly',
        p_premake         => 4,
        p_start_partition => (now())::text
    ); "/>
</modifySql>

IMPORTANT: All other objects, including column and table comments, must be in a separate XML file (_with the same XML header_).

. Oracle create table + BLOB + Partition SQL version:
[source,sql]
create table AMENDMENT_CATALOG
(
  x__id             VARCHAR2(30 CHAR) not null,
  amendment_catalog BLOB not null,
  valid_from        DATE default trunc(sysdate) not null,
  valid_to          DATE default to_date('9999.12.31','YYYY.MM.DD') not null,
  x__insdate        DATE default sysdate not null,
  x__insuser        VARCHAR2(30 CHAR) default '0' not null,
  x__moddate        DATE,
  x__moduser        VARCHAR2(30 CHAR),
  x__version        NUMBER default 0 not null
) LOB(amendment_catalog) STORE AS SECUREFILE(
    DEDUPLICATE
    COMPRESS LOW
)
partition by range (x__insdate)
   interval( numtoyminterval(1,'MONTH'))(
      partition p_start values less than (to_date('2021-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN'))
);

. Postgresql create table + BLOB + Partition SQL version:
[source,sql]
create table AMENDMENT_CATALOG
(
  x__id             VARCHAR(30) not null,
  amendment_catalog bytea not null,
  valid_from        timestamptz(6) default trunc(sysdate) not null,
  valid_to          timestamptz(6) default to_date('9999.12.31','YYYY.MM.DD') not null,
  insdate_month     timestamptz(6) default to_date(to_char(now(), 'YYYY.MM'), 'YYYY.MM') not null,
  x__insdate        timestamptz(6) default now() not null,
  x__insuser        VARCHAR(30) default '0' not null,
  x__moddate        timestamptz(6),
  x__moduser        VARCHAR(30),
  x__version        INT default 0 not null
);
PARTITION BY RANGE (insdate_month);
SELECT partman.create_parent( 
        p_parent_table    => 'AMENDMENT_CATALOG',
        p_control         => 'insdate_month',
        p_type            => 'native',
        p_interval        => 'monthly',
        p_premake         => 4,
        p_start_partition => (now())::text
);

*Separated remarks examples in case of XML BLOB or Partition:*
[source,xml]
<setTableRemarks remarks="Control tables for status modification and process operation/correction" schemaName="${schema_name}" tableName="nf_push"/>
<setColumnRemarks columnName="x__id" remarks="PK" tableName="nf_push" schemaName="${schema_name}"/>
<setColumnRemarks columnName="nf_data_id" remarks="FK - NF_DATA.X__ID" tableName="nf_push" schemaName="${schema_name}"/>
<setColumnRemarks columnName="device_token" remarks="The device token to which the message should be sent." tableName="nf_push" schemaName="${schema_name}"/>
<setColumnRemarks columnName="channel_id" remarks="Collector ID of devices subscribed to a specified channel." tableName="nf_push" schemaName="${schema_name"/>
<setColumnRemarks columnName="data" remarks="JSON formatted data containing unique key-value pairs." tableName="nf_push" schemaName="${schema_name}"/>
<setColumnRemarks columnName="x__insdate" remarks="The timestamp of insertion" tableName="nf_push" schemaName="${schema_name}"/>
<setColumnRemarks columnName="x__insuser" remarks="The identifier of the user performing the insertion (X__ID)" tableName="nf_push" schemaName="${schema_name}"/>
<setColumnRemarks columnName="x__moddate" remarks="The timestamp of modification" tableName="nf_push" schemaName="${schema_name}"/>
<setColumnRemarks columnName="x__moduser" remarks="The identifier of the user performing the modification (X__ID)" tableName="nf_push" schemaName="${schema_name}"/>
<setColumnRemarks columnName="x__version" remarks="Versioning of changes" tableName="nf_push" schemaName="${schema_name}"/>
<createIndex indexName="ix_nf_push_nf_data_id" tableName="nf_push" schemaName="${schema_name}">
    <column name="nf_data_id"/>
</createIndex>    
<addPrimaryKey columnNames="x__id" constraintName="pk_nf_push" tableName="nf_push" schemaName="${schema_name}" />
<addForeignKeyConstraint  baseColumnNames="nf_data_id"                                  
                          baseTableName="nf_push"
                          baseTableSchemaName="${schema_name}"
                          constraintName="fk_nf_push_nf_data"
                          referencedColumnNames="x__id"
                          referencedTableName="nf_data"
                          referencedTableSchemaName="${schema_name}"/>

IMPORTANT: FK indexes must be in a separate XML file (_with the same XML header_) in case of LOB or Partition and if there is a foreign key.

*FK index in case of XML BLOB or Partition:*
[source,xml]
<?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE defaultProperties SYSTEM "common/params.dtd">
    <databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
       http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.3.xsd">
    <!-- include the default properties -->
    &propertiesAll;
    <changeSet id="0005" author="jozsef.holczer" labels="0.1.0">
        <comment>PROJECT-44-Creating project_INVOICE table, Foreign Key index.</comment>
        <!-- FK Index -->
        <createIndex indexName = "ix_project_invoice_project_transaction_id" tableName = "project_invoice" schemaName = "${schema_name}">
            <column name = "project_transaction_id"/>
        </createIndex>
        <modifySql dbms = "oracle">
            <append  value = " LOCAL"/>
        </modifySql>
    </changeSet>
</databaseChangeLog>

======   
====