version: "3.8"

# run
# docker-compose -f <PATH>/etc/docker-compose/oracle/docker-compose.local.oracle.yml up --build --force-recreate
#
# docker exec -it module-dookug-oracle /bin/bash
# This is used to download (if it wasn't already) the free Oracle image and start it locally.
# This is for local testing.
services:
  module-dookug-oracle:
    container_name: module-dookug-oracle
    image: container-registry.oracle.com/database/express:21.3.0-xe
    ports:
      #(Oracle Listener)
      - '1521:1521'
      #(EM Express)
      - '5500:5500'
    environment:
      ORACLE_PWD: developer
      ORACLE_CHARACTERSET: AL32UTF8
    volumes:
      - dookug-db-oracle-data:/opt/oracle/oradata
networks: 
  default: 
    external: true
    name: dookug-local-network
volumes:
  dookug-db-oracle-data:
    name: dookug-db-oracle-data
