name: Docker compile

on:
  pull_request:
    branches-ignore:
      - 'gh-pages'
      - 'dependabot/**'

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.event.ref }}
        uses: actions/checkout@v4
      - name: Check the license in the files
        uses: pre-commit/action@v3.0.1
      - name: Enable BuildKit
        run: echo "DOCKER_BUILDKIT=1" >> $GITHUB_ENV
      - name: Load .env into environment
        run: |
          set -a
          source .env
          set +a  
      - name: Run docker-compose with bake
        run: |
          docker compose --env-file .env -f ./etc/release/docker-compose.yml bake --no-cache
