name: Docker compile

on:
  push:
    branches:
      - 'feature/**'

jobs:
  docker-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.event.ref }}
        uses: actions/checkout@v4
      - name: Check license header files
        uses: pre-commit/action@v3.0.1
      - name: Run docker-compose
        run: |
          docker compose -f ./etc/release/docker-compose.yml build --no-cache
