name: Docker compile

on:
  workflow_dispatch:
    inputs:
      comment:
        description: 'test check licence'
        default: 'test check licence'
        required: true

jobs:
  check-licence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ${{ github.event.ref }}
        uses: actions/checkout@v4
      - name: Check the license in the files
        uses: pre-commit/action@v3.0.1
